import { useState, useEffect, useRef, useCallback, useMemo } from 'react'
import Delaunator from 'delaunator'
import type { Project, Point2D, MeshData } from '../../types/project'
import type { UploadHint } from '../../db/projectsStore'
import TriangulationCanvas from '../triangulation/TriangulationCanvas'
import { useTriangulation } from '../triangulation/useTriangulation'
import { generateAutoMesh } from '../../utils/autoMeshGenerator'
import { generateTemplatePDF } from '../../utils/pdfGenerator'
import { computeAllBarycentrics, interpolateInternalPoint } from '../../utils/barycentricUtils'
import { precomputeARAP, batchSolveARAP } from '../../utils/arapSolver'
import { pointInPolygon, triangleCentroid } from '../../utils/geometry'
import { computeAllSubdivisionFrames } from '../../utils/curvilinearContour'
import { loadOpenCVWorker } from '../../utils/perspectiveCorrection'
import { applyTemporalSmoothing } from '../../utils/trackingConstraints'
import type { PointType } from '../triangulation/drawingUtils'

interface Props {
  project: Project
  onSave: (project: Project, uploadOnly?: UploadHint[]) => Promise<void>
}

export default function TriangulationStep({ project, onSave }: Props) {
  const [saving, setSaving] = useState(false)
  const [imageUrl, setImageUrl] = useState<string | null>(null)
  const [density, setDensity] = useState(5)
  const [generating, setGenerating] = useState(false)
  const isAutoGenerated = useRef(false)

  const mesh = project.mesh
  const contourAnchors = mesh?.contourAnchors ?? []
  const contourSubPts = mesh?.contourSubdivisionPoints ?? []
  const contourSubParams = mesh?.contourSubdivisionParams ?? []
  const anchorPoints = mesh?.anchorPoints ?? []

  // Ordered contour polygon: anchor0 → sub_seg0 → anchor1 → sub_seg1 → ...
  // This is the proper winding-order polygon for pointInPolygon filtering
  const orderedContour = useMemo(() => {
    const n = contourAnchors.length
    if (n < 3) return contourAnchors
    const result: Point2D[] = []
    for (let i = 0; i < n; i++) {
      result.push(contourAnchors[i])
      // Collect subdivision points for this segment, sorted by t
      const segPts: { t: number; point: Point2D }[] = []
      for (let j = 0; j < contourSubParams.length; j++) {
        if (contourSubParams[j].segmentIndex === i) {
          segPts.push({ t: contourSubParams[j].t, point: contourSubPts[j] })
        }
      }
      segPts.sort((a, b) => a.t - b.t)
      for (const sp of segPts) {
        result.push(sp.point)
      }
    }
    return result
  }, [contourAnchors, contourSubPts, contourSubParams])

  // Tracked points = contour anchors + internal anchors (for barycentric interpolation)
  const trackedPoints = useMemo(() => [...contourAnchors, ...anchorPoints], [contourAnchors, anchorPoints])
  // All base points for Delaunay (order must match videoFramesMesh convention)
  const allBasePoints = useMemo(() => [...contourAnchors, ...contourSubPts, ...anchorPoints], [contourAnchors, contourSubPts, anchorPoints])
  const topologyLocked = mesh?.topologyLocked ?? false
  const hasAnimation = mesh?.videoFramesMesh != null

  // Animation state
  const [computing, setComputing] = useState(false)
  const [animProgress, setAnimProgress] = useState('')
  const [smoothingWindow, setSmoothingWindow] = useState(3)
  const [playing, setPlaying] = useState(false)
  const [currentFrame, setCurrentFrame] = useState(0)
  const animCanvasRef = useRef<HTMLCanvasElement>(null)
  const animContainerRef = useRef<HTMLDivElement>(null)
  const videoRef = useRef<HTMLVideoElement | null>(null)
  const [videoReady, setVideoReady] = useState(false)
  const animFrameRef = useRef(0)
  const [imageDims, setImageDims] = useState<{ w: number; h: number } | null>(null)
  const [viewMode, setViewMode] = useState<'video' | 'wireframe' | 'gradient'>('video')
  // Pre-computed gradient colors per triangle (HSL based on centroid at frame 0)
  const gradientColors = useRef<string[]>([])

  const {
    internalPoints,
    triangles,
    addInternalPoint,
    movePoint,
    deletePoint,
    loadAutoMesh,
  } = useTriangulation(
    mesh
      ? {
          contourPoints: orderedContour,
          internalPoints: mesh.internalPoints,
          triangles: mesh.triangles,
        }
      : undefined,
    allBasePoints.length > 0 ? allBasePoints : undefined,
    orderedContour.length >= 3 ? orderedContour : undefined
  )

  useEffect(() => {
    if (!project.originalImageBlob) {
      setImageUrl(null)
      return
    }
    const url = URL.createObjectURL(project.originalImageBlob)
    setImageUrl(url)
    return () => URL.revokeObjectURL(url)
  }, [project.originalImageBlob])

  const runAutoInternalPoints = useCallback(async (d: number) => {
    if (!project.originalImageBlob) return
    setGenerating(true)
    try {
      const result = await generateAutoMesh(project.originalImageBlob, d)
      loadAutoMesh(orderedContour, result.internalPoints)
      isAutoGenerated.current = true
    } catch (err) {
      console.error('Auto internal points failed:', err)
    } finally {
      setGenerating(false)
    }
  }, [project.originalImageBlob, loadAutoMesh, orderedContour])

  function handleDensityChange(delta: number) {
    const newDensity = Math.max(1, Math.min(10, density + delta))
    setDensity(newDensity)
    if (isAutoGenerated.current) {
      runAutoInternalPoints(newDensity)
    }
  }

  function handleClearInternalPoints() {
    loadAutoMesh(orderedContour, [])
    isAutoGenerated.current = false
  }

  const handleMovePoint = useCallback((type: PointType, index: number, p: Point2D) => {
    if (type === 'internal') {
      movePoint('internal', index, p)
    }
  }, [movePoint])

  const handleDeletePoint = useCallback((type: PointType, index: number) => {
    if (type === 'internal') {
      deletePoint('internal', index)
    }
  }, [deletePoint])

  async function handleLockTopology() {
    if (!mesh || trackedPoints.length < 3) return
    setSaving(true)
    try {
      // Delaunay on tracked points (contour + anchors)
      const coords = new Float64Array(trackedPoints.length * 2)
      trackedPoints.forEach((p, i) => {
        coords[i * 2] = p.x
        coords[i * 2 + 1] = p.y
      })
      const delaunay = new Delaunator(coords)
      const trackedTriangles: [number, number, number][] = []
      for (let i = 0; i < delaunay.triangles.length; i += 3) {
        const a = delaunay.triangles[i]
        const b = delaunay.triangles[i + 1]
        const c = delaunay.triangles[i + 2]
        const centroid = triangleCentroid(trackedPoints[a], trackedPoints[b], trackedPoints[c])
        if (pointInPolygon(centroid, orderedContour)) {
          trackedTriangles.push([a, b, c])
        }
      }

      // Compute barycentrics for internal points relative to tracked points
      const internalBarycentrics = computeAllBarycentrics(
        internalPoints,
        trackedPoints,
        trackedTriangles
      )

      const updatedMesh: MeshData = {
        ...mesh,
        internalPoints,
        triangles,
        topologyLocked: true,
        trackedTriangles,
        internalBarycentrics,
      }

      await onSave({ ...project, mesh: updatedMesh })
    } catch (err) {
      console.error('Failed to lock topology:', err)
      alert('Erreur : ' + (err instanceof Error ? err.message : err))
    }
    setSaving(false)
  }

  async function handleUnlockTopology() {
    if (!mesh) return
    if (!confirm('Déverrouiller la topologie supprimera les données d\'animation. Continuer ?')) return
    setSaving(true)
    try {
      const updatedMesh: MeshData = {
        ...mesh,
        topologyLocked: false,
        trackedTriangles: [],
        internalBarycentrics: [],
        videoFramesMesh: null,
      }
      await onSave({ ...project, mesh: updatedMesh })
    } catch (err) {
      console.error('Failed to unlock topology:', err)
    }
    setSaving(false)
  }

  async function handleSave() {
    if (!mesh) return
    setSaving(true)
    try {
      const updatedMesh: MeshData = {
        ...mesh,
        internalPoints,
        triangles,
      }
      await onSave({ ...project, mesh: updatedMesh })
    } catch (err) {
      console.error('Failed to save mesh:', err)
      alert('Erreur lors de la sauvegarde : ' + (err instanceof Error ? err.message : err))
    }
    setSaving(false)
  }

  // --- Animation computation ---

  // Load image dimensions
  useEffect(() => {
    if (!project.originalImageBlob) return
    const url = URL.createObjectURL(project.originalImageBlob)
    const img = new Image()
    img.onload = () => {
      setImageDims({ w: img.naturalWidth, h: img.naturalHeight })
      URL.revokeObjectURL(url)
    }
    img.onerror = () => URL.revokeObjectURL(url)
    img.src = url
  }, [project.originalImageBlob])

  // Load video for preview
  useEffect(() => {
    if (!project.videoBlob) return
    const url = URL.createObjectURL(project.videoBlob)
    const video = document.createElement('video')
    video.src = url
    video.muted = true
    video.playsInline = true
    video.preload = 'auto'
    video.onloadeddata = () => {
      videoRef.current = video
      setVideoReady(true)
    }
    video.load()
    return () => { video.pause(); URL.revokeObjectURL(url) }
  }, [project.videoBlob])

  // Canvas resize
  useEffect(() => {
    const container = animContainerRef.current
    const canvas = animCanvasRef.current
    if (!container || !canvas) return
    const observer = new ResizeObserver(entries => {
      const { width, height } = entries[0].contentRect
      if (width === 0 || height === 0) return
      const dpr = window.devicePixelRatio || 1
      canvas.width = width * dpr
      canvas.height = height * dpr
      canvas.style.width = `${width}px`
      canvas.style.height = `${height}px`
    })
    observer.observe(container)
    return () => observer.disconnect()
  }, [hasAnimation])

  // Compute gradient colors per triangle from frame 0 positions
  useEffect(() => {
    if (!hasAnimation) return
    const frames = mesh!.videoFramesMesh!
    const tris = mesh!.triangles
    const pts0 = frames[0]
    if (!pts0 || tris.length === 0) return

    // Compute bounding box of frame 0
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity
    for (const p of pts0) {
      if (p.x < minX) minX = p.x
      if (p.y < minY) minY = p.y
      if (p.x > maxX) maxX = p.x
      if (p.y > maxY) maxY = p.y
    }
    const w = maxX - minX || 1
    const h = maxY - minY || 1

    // Assign each triangle a color based on its centroid position (2D gradient)
    gradientColors.current = tris.map(([a, b, c]) => {
      if (a >= pts0.length || b >= pts0.length || c >= pts0.length) return '#888'
      const cx = (pts0[a].x + pts0[b].x + pts0[c].x) / 3
      const cy = (pts0[a].y + pts0[b].y + pts0[c].y) / 3
      const nx = (cx - minX) / w // 0..1 horizontal
      const ny = (cy - minY) / h // 0..1 vertical
      const hue = (nx * 300 + ny * 60) % 360
      const sat = 70 + ny * 20
      const light = 45 + nx * 20
      return `hsl(${hue}, ${sat}%, ${light}%)`
    })
  }, [hasAnimation, mesh])

  // Animation playback loop
  useEffect(() => {
    if (!hasAnimation || !playing) return
    const frames = mesh!.videoFramesMesh!
    let lastTime = performance.now()
    function tick(now: number) {
      if (now - lastTime >= 1000 / 24) {
        lastTime = now
        setCurrentFrame(f => (f + 1) % frames.length)
      }
      animFrameRef.current = requestAnimationFrame(tick)
    }
    animFrameRef.current = requestAnimationFrame(tick)
    return () => cancelAnimationFrame(animFrameRef.current)
  }, [hasAnimation, playing, mesh])

  // Draw animation frame
  useEffect(() => {
    if (!hasAnimation) return
    // Video mode requires video ready; other modes don't
    if (viewMode === 'video' && !videoReady) return
    const canvas = animCanvasRef.current
    const video = videoRef.current
    const frames = mesh!.videoFramesMesh!
    const tris = mesh!.triangles
    if (!canvas || currentFrame >= frames.length) return
    if (viewMode === 'video' && !video) return

    // Ensure canvas has dimensions (ResizeObserver may not have fired yet)
    if (canvas.width === 0 || canvas.height === 0) {
      const rect = canvas.getBoundingClientRect()
      if (rect.width > 0 && rect.height > 0) {
        const dpr = window.devicePixelRatio || 1
        canvas.width = rect.width * dpr
        canvas.height = rect.height * dpr
      }
    }

    const frame = currentFrame
    const targetTime = frame / 24
    const mode = viewMode
    const colors = gradientColors.current

    function draw() {
      const ctx = canvas!.getContext('2d')
      if (!ctx) return
      const dpr = window.devicePixelRatio || 1
      // Clear at full physical resolution before applying DPR transform
      ctx.setTransform(1, 0, 0, 1, 0, 0)
      ctx.clearRect(0, 0, canvas!.width, canvas!.height)
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0)
      const cssW = canvas!.width / dpr
      const cssH = canvas!.height / dpr
      if (cssW === 0 || cssH === 0) return

      const vw = video?.videoWidth ?? imageDims?.w ?? 800
      const vh = video?.videoHeight ?? imageDims?.h ?? 600
      const s = Math.min(cssW / vw, cssH / vh) * 0.95
      const ox = (cssW - vw * s) / 2, oy = (cssH - vh * s) / 2
      const imgW = imageDims?.w ?? vw, imgH = imageDims?.h ?? vh
      const points = frames[frame]

      // Background
      if (mode === 'video' && video) {
        ctx.drawImage(video, ox, oy, vw * s, vh * s)
      } else {
        // Dark background for wireframe and gradient modes
        ctx.fillStyle = '#1a1a2e'
        ctx.fillRect(ox, oy, vw * s, vh * s)
      }

      // Helper to convert mesh coords to canvas coords
      const toCanvas = (p: Point2D) => ({
        x: (p.x / imgW) * vw * s + ox,
        y: (p.y / imgH) * vh * s + oy,
      })

      if (mode === 'gradient') {
        // Filled triangles with gradient colors
        for (let ti = 0; ti < tris.length; ti++) {
          const [a, b, c] = tris[ti]
          if (a >= points.length || b >= points.length || c >= points.length) continue
          const pa = toCanvas(points[a]), pb = toCanvas(points[b]), pc = toCanvas(points[c])
          ctx.fillStyle = colors[ti] ?? '#888'
          ctx.beginPath()
          ctx.moveTo(pa.x, pa.y)
          ctx.lineTo(pb.x, pb.y)
          ctx.lineTo(pc.x, pc.y)
          ctx.closePath()
          ctx.fill()
        }
        // Thin wireframe overlay
        ctx.strokeStyle = 'rgba(255, 255, 255, 0.15)'
        ctx.lineWidth = 0.5
        for (const [a, b, c] of tris) {
          if (a >= points.length || b >= points.length || c >= points.length) continue
          const pa = toCanvas(points[a]), pb = toCanvas(points[b]), pc = toCanvas(points[c])
          ctx.beginPath()
          ctx.moveTo(pa.x, pa.y)
          ctx.lineTo(pb.x, pb.y)
          ctx.lineTo(pc.x, pc.y)
          ctx.closePath()
          ctx.stroke()
        }
      } else {
        // Wireframe (both video and wireframe modes)
        ctx.strokeStyle = mode === 'video' ? 'rgba(0, 255, 100, 0.4)' : 'rgba(0, 255, 200, 0.7)'
        ctx.lineWidth = mode === 'video' ? 1 : 1.2
        for (const [a, b, c] of tris) {
          if (a >= points.length || b >= points.length || c >= points.length) continue
          const pa = toCanvas(points[a]), pb = toCanvas(points[b]), pc = toCanvas(points[c])
          ctx.beginPath()
          ctx.moveTo(pa.x, pa.y)
          ctx.lineTo(pb.x, pb.y)
          ctx.lineTo(pc.x, pc.y)
          ctx.closePath()
          ctx.stroke()
        }
      }

      // Draw vertices by category
      const nCA = mesh!.contourAnchors.length
      const nSub = mesh!.contourSubdivisionPoints.length
      const nAP = mesh!.anchorPoints.length
      // allPoints = [...contourAnchors(nCA), ...subdivision(nSub), ...anchorPoints(nAP), ...internals]
      for (let i = 0; i < points.length; i++) {
        const p = toCanvas(points[i])
        let color: string
        let radius: number
        if (i < nCA) {
          // Contour anchors — red
          color = 'rgba(255, 60, 60, 0.9)'
          radius = 3.5
        } else if (i < nCA + nSub) {
          // Subdivision — yellow
          color = 'rgba(255, 220, 50, 0.8)'
          radius = 2
        } else if (i < nCA + nSub + nAP) {
          // Internal anchors — cyan
          color = 'rgba(0, 200, 255, 0.9)'
          radius = 3.5
        } else {
          // Internal (barycentric) — white
          color = 'rgba(255, 255, 255, 0.7)'
          radius = 2
        }
        ctx.beginPath()
        ctx.arc(p.x, p.y, radius, 0, Math.PI * 2)
        ctx.fillStyle = color
        ctx.fill()
      }

      // Frame counter
      ctx.fillStyle = 'rgba(0,0,0,0.6)'
      ctx.fillRect(8, 8, 120, 24)
      ctx.fillStyle = '#fff'
      ctx.font = '12px monospace'
      ctx.fillText(`Frame ${frame} / ${frames.length - 1}`, 14, 24)
    }

    if (mode === 'video' && video) {
      const handleSeeked = () => draw()
      video.addEventListener('seeked', handleSeeked)
      video.currentTime = targetTime
      if (Math.abs(video.currentTime - targetTime) < 0.02) {
        draw()
      }
      return () => {
        video.removeEventListener('seeked', handleSeeked)
      }
    } else {
      // No video seek needed for wireframe/gradient modes
      draw()
    }
  }, [hasAnimation, videoReady, currentFrame, mesh, imageDims, viewMode])

  async function handleComputeAnimation() {
    if (!mesh || !mesh.contourAnchorFrames) return
    const contourAnchorFrames = mesh.contourAnchorFrames
    const ancFrames = mesh.anchorFrames ?? []
    const trackedTris = mesh.trackedTriangles
    const intBary = mesh.internalBarycentrics

    const totalF = ancFrames.length > 0
      ? Math.min(contourAnchorFrames.length, ancFrames.length)
      : contourAnchorFrames.length
    if (totalF === 0) return

    setComputing(true)

    try {
      // Use cached subdivision frames if available, otherwise recompute
      let contourSubFrames = mesh.contourSubdivisionFrames
      if (!contourSubFrames && mesh.contourSubdivisionParams.length > 0 && mesh.cannyParams && imageDims) {
        setAnimProgress('Calcul positions contour subdivision...')
        if (!mesh.contourCannyFrames) await loadOpenCVWorker()
        const subdivResult = await computeAllSubdivisionFrames(
          project.videoBlob!,
          contourAnchorFrames,
          mesh.contourSubdivisionParams,
          mesh.cannyParams,
          imageDims.w,
          imageDims.h,
          (p) => setAnimProgress(`Subdivision frame ${p.frame}/${p.total}`),
          mesh.contourOriginFrames,
          mesh.contourCannyFrames
        )
        contourSubFrames = subdivResult.subdivisionFrames
      }

      setAnimProgress('Calcul animation...')
      const videoFramesMesh: Point2D[][] = []

      // DEBUG: log sizes at frame 0
      console.log('[ANIM DEBUG] contourAnchors.length:', mesh.contourAnchors.length)
      console.log('[ANIM DEBUG] anchorPoints.length:', mesh.anchorPoints.length)
      console.log('[ANIM DEBUG] contourSubdivisionPoints.length:', mesh.contourSubdivisionPoints.length)
      console.log('[ANIM DEBUG] internalPoints.length:', mesh.internalPoints.length)
      console.log('[ANIM DEBUG] trackedTriangles.length:', trackedTris.length)
      console.log('[ANIM DEBUG] internalBarycentrics.length:', intBary.length)
      console.log('[ANIM DEBUG] totalFrames:', totalF)
      console.log('[ANIM DEBUG] contourAnchorFrames.length:', contourAnchorFrames.length)
      console.log('[ANIM DEBUG] ancFrames.length:', ancFrames.length)
      console.log('[ANIM DEBUG] contourSubFrames?.length:', contourSubFrames?.length)

      for (let f = 0; f < totalF; f++) {
        if (f % 10 === 0) {
          setAnimProgress(`Frame ${f + 1} / ${totalF}`)
          await new Promise(r => setTimeout(r, 0))
        }

        // Tracked positions for barycentric interpolation
        const trackedPositions = [...contourAnchorFrames[f], ...(ancFrames[f] ?? anchorPoints)]

        // Subdivision positions (from curvilinear computation)
        const subPositions = contourSubFrames?.[f] ?? mesh.contourSubdivisionPoints

        // DEBUG: log details for frames around the collapse (11-14)
        if (f >= 11 && f <= 14) {
          console.log(`[ANIM DEBUG] === Frame ${f} ===`)
          console.log(`  contourAnchorFrames[${f}].length:`, contourAnchorFrames[f]?.length)
          console.log(`  ancFrames[${f}].length:`, ancFrames[f]?.length)
          console.log(`  subPositions.length:`, subPositions?.length)
          console.log(`  trackedPositions.length:`, trackedPositions.length)

          // Check for NaN/undefined in tracked positions
          const badTracked = trackedPositions.filter((p, i) =>
            !p || isNaN(p.x) || isNaN(p.y)
          )
          if (badTracked.length > 0) {
            console.warn(`  ⚠️ ${badTracked.length} BAD tracked positions (NaN/undefined)`)
          }

          // Check for NaN/zero in subdivision
          const badSub = subPositions?.filter(p => !p || isNaN(p.x) || isNaN(p.y) || (p.x === 0 && p.y === 0))
          if (badSub && badSub.length > 0) {
            console.warn(`  ⚠️ ${badSub.length} BAD/zero subdivision positions`)
          }

          // Log contour anchor positions
          console.log(`  contourAnchors:`, contourAnchorFrames[f]?.map((p: Point2D) => `(${p.x.toFixed(1)},${p.y.toFixed(1)})`))
          // Log internal anchor positions
          console.log(`  anchorPoints:`, ancFrames[f]?.map((p: Point2D) => `(${p.x.toFixed(1)},${p.y.toFixed(1)})`))

          // Log first few subdivision positions
          console.log(`  subPositions[0..4]:`, subPositions?.slice(0, 5).map((p: Point2D) => `(${p.x.toFixed(1)},${p.y.toFixed(1)})`))
        }

        // Internal points via barycentrics
        const internalPositions = intBary.map(bary =>
          interpolateInternalPoint(bary, trackedPositions, trackedTris)
        )

        // DEBUG: log internal positions for collapse frames
        if (f >= 11 && f <= 14) {
          const badInternal = internalPositions.filter(p => isNaN(p.x) || isNaN(p.y))
          if (badInternal.length > 0) {
            console.warn(`  ⚠️ ${badInternal.length} NaN internal positions`)
          }
          // Compute bounding box of internal positions to detect collapse
          const xs = internalPositions.map(p => p.x)
          const ys = internalPositions.map(p => p.y)
          const bbox = {
            minX: Math.min(...xs).toFixed(1), maxX: Math.max(...xs).toFixed(1),
            minY: Math.min(...ys).toFixed(1), maxY: Math.max(...ys).toFixed(1),
          }
          console.log(`  internalPositions bbox:`, bbox)
          console.log(`  internalPositions spread: ${(Math.max(...xs) - Math.min(...xs)).toFixed(1)} x ${(Math.max(...ys) - Math.min(...ys)).toFixed(1)}`)
        }

        // allPoints = [...contourAnchors, ...contourSubdivisionPoints, ...anchorPoints, ...internalPoints]
        videoFramesMesh.push([
          ...contourAnchorFrames[f],
          ...subPositions,
          ...(ancFrames[f] ?? anchorPoints),
          ...internalPositions,
        ])
      }

      // Temporal smoothing to reduce jitter
      if (smoothingWindow > 1) {
        setAnimProgress('Lissage temporel...')
        await new Promise(r => setTimeout(r, 0))
        const smoothed = applyTemporalSmoothing(videoFramesMesh, smoothingWindow)
        videoFramesMesh.length = 0
        videoFramesMesh.push(...smoothed)
      }

      setAnimProgress('Sauvegarde...')
      const updatedMesh: MeshData = {
        ...mesh,
        contourSubdivisionFrames: contourSubFrames,
        contourSubdivisionValidated: true,
        videoFramesMesh,
      }
      await onSave({ ...project, mesh: updatedMesh }, ['contourSubdivisionFrames', 'videoFramesMesh'])
      setComputing(false)
      setAnimProgress('')
    } catch (err) {
      console.error('Animation computation failed:', err)
      alert('Erreur : ' + (err instanceof Error ? err.message : err))
      setComputing(false)
      setAnimProgress('')
    }
  }

  async function handleComputeARAP() {
    if (!mesh || !mesh.contourAnchorFrames) return
    const contourAnchorFrames = mesh.contourAnchorFrames
    const ancFrames = mesh.anchorFrames ?? []

    const totalF = ancFrames.length > 0
      ? Math.min(contourAnchorFrames.length, ancFrames.length)
      : contourAnchorFrames.length
    if (totalF === 0) return

    setComputing(true)

    try {
      // Use cached subdivision frames if available, otherwise recompute
      let contourSubFrames = mesh.contourSubdivisionFrames
      if (!contourSubFrames && mesh.contourSubdivisionParams.length > 0 && mesh.cannyParams && imageDims) {
        setAnimProgress('Calcul positions contour subdivision...')
        if (!mesh.contourCannyFrames) await loadOpenCVWorker()
        const subdivResult = await computeAllSubdivisionFrames(
          project.videoBlob!,
          contourAnchorFrames,
          mesh.contourSubdivisionParams,
          mesh.cannyParams,
          imageDims.w,
          imageDims.h,
          (p) => setAnimProgress(`Subdivision frame ${p.frame}/${p.total}`),
          mesh.contourOriginFrames,
          mesh.contourCannyFrames
        )
        contourSubFrames = subdivResult.subdivisionFrames
      }
      // Build frame 0 allPoints for ARAP rest pose — use ORIGINAL mesh positions
      // (same as the ones used for Delaunay triangulation), not tracked frame 0
      const allPoints0: Point2D[] = [
        ...contourAnchors,
        ...contourSubPts,
        ...anchorPoints,
        ...mesh.internalPoints,
      ]

      // Pinned indices = all except internalPoints (last N)
      const nPinned = contourAnchors.length + contourSubPts.length + anchorPoints.length
      const pinnedIndices: number[] = []
      for (let i = 0; i < nPinned; i++) {
        pinnedIndices.push(i)
      }

      setAnimProgress('Pré-calcul ARAP (factorisation)...')
      await new Promise(r => setTimeout(r, 0))
      const arapSystem = precomputeARAP(allPoints0, mesh.triangles, pinnedIndices)

      // Build pinned positions per frame
      setAnimProgress('Calcul ARAP frames...')
      await new Promise(r => setTimeout(r, 0))

      const allPinnedFrames: Point2D[][] = []
      for (let f = 0; f < totalF; f++) {
        const subPositions = contourSubFrames?.[f] ?? mesh.contourSubdivisionPoints
        allPinnedFrames.push([
          ...contourAnchorFrames[f],
          ...subPositions,
          ...(ancFrames[f] ?? anchorPoints),
        ])
      }

      // DEBUG: log ARAP setup
      console.log('[ARAP DEBUG] nAll:', arapSystem.nAll)
      console.log('[ARAP DEBUG] nFree:', arapSystem.nFree)
      console.log('[ARAP DEBUG] nPinned:', arapSystem.pinnedIndices.length)
      console.log('[ARAP DEBUG] freeIndices:', arapSystem.freeIndices)
      console.log('[ARAP DEBUG] totalFrames:', totalF)
      console.log('[ARAP DEBUG] pinnedFrame[0].length:', allPinnedFrames[0]?.length)

      let videoFramesMesh = batchSolveARAP(
        arapSystem,
        allPinnedFrames,
        3,
        (frame, total) => setAnimProgress(`ARAP frame ${frame + 1} / ${total}`)
      )

      // DEBUG: log frames around the collapse
      for (let f = Math.max(0, 11); f <= Math.min(14, videoFramesMesh.length - 1); f++) {
        const pts = videoFramesMesh[f]
        const nCA = contourAnchors.length
        const nSub = contourSubPts.length
        const nAP = anchorPoints.length
        const freeStart = nCA + nSub + nAP

        // Pinned positions bounding box
        const pinnedPts = pts.slice(0, freeStart)
        const pinnedXs = pinnedPts.map(p => p.x)
        const pinnedYs = pinnedPts.map(p => p.y)

        // Free (internal) positions bounding box
        const freePts = pts.slice(freeStart)
        const freeXs = freePts.map(p => p.x)
        const freeYs = freePts.map(p => p.y)

        console.log(`[ARAP DEBUG] === Frame ${f} ===`)
        console.log(`  pinned bbox: x[${Math.min(...pinnedXs).toFixed(1)}..${Math.max(...pinnedXs).toFixed(1)}] y[${Math.min(...pinnedYs).toFixed(1)}..${Math.max(...pinnedYs).toFixed(1)}]`)
        console.log(`  free bbox:   x[${Math.min(...freeXs).toFixed(1)}..${Math.max(...freeXs).toFixed(1)}] y[${Math.min(...freeYs).toFixed(1)}..${Math.max(...freeYs).toFixed(1)}]`)
        console.log(`  free spread: ${(Math.max(...freeXs) - Math.min(...freeXs)).toFixed(1)} x ${(Math.max(...freeYs) - Math.min(...freeYs)).toFixed(1)}`)

        // Check for NaN
        const nanCount = freePts.filter(p => isNaN(p.x) || isNaN(p.y)).length
        if (nanCount > 0) console.warn(`  ⚠️ ${nanCount} NaN free positions!`)

        // Check pinned input vs output match
        const pinnedInput = allPinnedFrames[f]
        let mismatch = 0
        for (let i = 0; i < Math.min(pinnedInput.length, freeStart); i++) {
          if (Math.abs(pts[i].x - pinnedInput[i].x) > 0.01 || Math.abs(pts[i].y - pinnedInput[i].y) > 0.01) {
            mismatch++
          }
        }
        if (mismatch > 0) console.warn(`  ⚠️ ${mismatch} pinned position mismatches (input vs output)!`)

        // Centroid of free points
        const cx = freeXs.reduce((a, b) => a + b, 0) / freeXs.length
        const cy = freeYs.reduce((a, b) => a + b, 0) / freeYs.length
        console.log(`  free centroid: (${cx.toFixed(1)}, ${cy.toFixed(1)})`)

        // Compare pinned input positions vs previous frame to find jumps
        if (f > 0) {
          const prevPinned = allPinnedFrames[f - 1]
          const curPinned = allPinnedFrames[f]
          const jumps: string[] = []
          for (let i = 0; i < curPinned.length; i++) {
            const dx = curPinned[i].x - prevPinned[i].x
            const dy = curPinned[i].y - prevPinned[i].y
            const dist = Math.sqrt(dx * dx + dy * dy)
            if (dist > 5) {
              let cat = ''
              if (i < nCA) cat = `contourAnchor[${i}]`
              else if (i < nCA + nSub) cat = `subdivision[${i - nCA}]`
              else cat = `anchorPoint[${i - nCA - nSub}]`
              jumps.push(`${cat}: ${dist.toFixed(1)}px (${prevPinned[i].x.toFixed(1)},${prevPinned[i].y.toFixed(1)})→(${curPinned[i].x.toFixed(1)},${curPinned[i].y.toFixed(1)})`)
            }
          }
          if (jumps.length > 0) {
            console.warn(`  ⚠️ ${jumps.length} pinned points jumped >5px vs prev frame:`)
            jumps.forEach(j => console.warn(`    ${j}`))
          } else {
            console.log(`  all pinned points moved <5px vs prev frame`)
          }
        }
      }

      // Temporal smoothing to reduce jitter
      if (smoothingWindow > 1) {
        setAnimProgress('Lissage temporel...')
        await new Promise(r => setTimeout(r, 0))
        videoFramesMesh = applyTemporalSmoothing(videoFramesMesh, smoothingWindow)
      }

      // Yield to UI periodically
      setAnimProgress('Sauvegarde...')
      await new Promise(r => setTimeout(r, 0))

      const updatedMesh: MeshData = {
        ...mesh,
        contourSubdivisionFrames: contourSubFrames,
        contourSubdivisionValidated: true,
        videoFramesMesh,
      }
      await onSave({ ...project, mesh: updatedMesh }, ['contourSubdivisionFrames', 'videoFramesMesh'])
      setComputing(false)
      setAnimProgress('')
    } catch (err) {
      console.error('ARAP computation failed:', err)
      alert('Erreur ARAP : ' + (err instanceof Error ? err.message : err))
      setComputing(false)
      setAnimProgress('')
    }
  }

  async function handleGeneratePDF() {
    try {
      const blob = await generateTemplatePDF(project)
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${project.name}-template.pdf`
      a.click()
      URL.revokeObjectURL(url)
    } catch (err) {
      console.error('PDF generation failed:', err)
      alert('Erreur PDF : ' + (err instanceof Error ? err.message : err))
    }
  }

  if (!mesh?.anchorTrackingValidated) {
    return (
      <div className="placeholder">
        Validez d&apos;abord le tracking des ancres (étape 7).
      </div>
    )
  }

  if (trackedPoints.length < 3) {
    return (
      <div className="placeholder">
        Il faut au minimum 3 points trackés (contour + ancres) pour trianguler.
      </div>
    )
  }

  return (
    <div className="triangulation-step">
      <div className="triangulation-toolbar">
        {topologyLocked && (
          <span style={{ color: '#22c55e', fontWeight: 'bold', marginRight: 8 }}>
            Topologie verrouillée
          </span>
        )}

        {!topologyLocked && (
          <>
            <button onClick={() => runAutoInternalPoints(density)} disabled={generating}>
              {generating ? 'Génération...' : 'Auto points internes'}
            </button>

            <button
              onClick={() => handleDensityChange(-1)}
              disabled={density <= 1 || generating}
              title="Moins de points"
            >
              −
            </button>
            <span className="density-label">Densité: {density}</span>
            <button
              onClick={() => handleDensityChange(1)}
              disabled={density >= 10 || generating}
              title="Plus de points"
            >
              +
            </button>

            <span className="toolbar-separator" />

            <button onClick={handleSave} disabled={saving}>
              {saving ? 'Sauvegarde...' : 'Sauvegarder'}
            </button>
            <button
              onClick={handleLockTopology}
              disabled={saving || triangles.length === 0}
              style={{ background: '#22c55e', color: 'white' }}
            >
              Verrouiller la topologie
            </button>
            <button className="btn-danger" onClick={handleClearInternalPoints}>
              Effacer internes
            </button>
          </>
        )}

        {topologyLocked && (
          <button className="btn-danger" onClick={handleUnlockTopology} disabled={saving}>
            Déverrouiller
          </button>
        )}

        <span className="toolbar-separator" />

        <button onClick={handleGeneratePDF}>
          Télécharger PDF
        </button>

        <span className="toolbar-info">
          Contour: {contourAnchors.length}+{contourSubPts.length} |
          Ancres: {anchorPoints.length} |
          Internes: {internalPoints.length} |
          Triangles: {triangles.length}
        </span>
      </div>

      <div className="triangulation-help">
        {topologyLocked ? (
          <span>
            La topologie est verrouillée. Calculez l&apos;animation ci-dessous.
          </span>
        ) : (
          <span>
            Clic gauche = ajouter un point interne | Glisser = déplacer | Clic droit = supprimer |
            Contour et ancres (bleus + orange) sont en lecture seule.
          </span>
        )}
      </div>

      <TriangulationCanvas
        imageUrl={imageUrl}
        contourPoints={orderedContour}
        internalPoints={topologyLocked ? mesh.internalPoints : internalPoints}
        triangles={topologyLocked ? mesh.triangles : triangles}
        contourClosed={true}
        mode="internal"
        onAddContourPoint={() => {}}
        onInsertContourPoint={() => {}}
        onCloseContour={() => {}}
        onAddInternalPoint={topologyLocked ? () => {} : addInternalPoint}
        onMovePoint={topologyLocked ? () => {} : handleMovePoint}
        onDeletePoint={topologyLocked ? () => {} : handleDeletePoint}
        anchorPoints={allBasePoints}
        readOnlyAnchors={true}
      />

      {/* Animation section (when topology locked) */}
      {topologyLocked && (
        <div style={{ borderTop: '2px solid #333', marginTop: 8 }}>
          <div style={{ padding: '12px 16px', display: 'flex', alignItems: 'center', gap: 12 }}>
            {!hasAnimation ? (
              <>
                <button
                  onClick={handleComputeAnimation}
                  disabled={computing}
                  style={{ background: '#2563eb', color: 'white', padding: '8px 24px' }}
                >
                  {computing ? 'Calcul en cours...' : 'Barycentrique'}
                </button>
                <button
                  onClick={handleComputeARAP}
                  disabled={computing}
                  style={{ background: '#9333ea', color: 'white', padding: '8px 24px' }}
                >
                  {computing ? 'Calcul en cours...' : 'Calculer ARAP'}
                </button>
                <label style={{ display: 'flex', alignItems: 'center', gap: 4, fontSize: 12, color: '#aaa' }}>
                  Lissage :
                  <input type="range" min={1} max={11} step={2}
                    value={smoothingWindow}
                    onChange={e => setSmoothingWindow(Number(e.target.value))}
                    disabled={computing}
                    style={{ width: 80 }} />
                  <span style={{ fontFamily: 'monospace', minWidth: 16 }}>{smoothingWindow}</span>
                </label>
                {computing && <span style={{ fontFamily: 'monospace', color: '#888' }}>{animProgress}</span>}
              </>
            ) : (
              <>
                <span style={{ color: '#22c55e', fontWeight: 'bold' }}>Animation calculée</span>
                <span style={{ color: '#888' }}>
                  {mesh.videoFramesMesh!.length} frames, {mesh.videoFramesMesh![0]?.length ?? 0} pts/frame
                </span>
                <button onClick={() => setPlaying(!playing)}>{playing ? 'Pause' : 'Play'}</button>
                <button onClick={() => { setPlaying(false); setCurrentFrame(f => Math.max(0, f - 1)) }} title="Frame précédente">
                  ◀
                </button>
                <button onClick={() => { setPlaying(false); setCurrentFrame(f => Math.min(mesh!.videoFramesMesh!.length - 1, f + 1)) }} title="Frame suivante">
                  ▶
                </button>
                <button onClick={() => { setPlaying(false); setCurrentFrame(0) }}>Rewind</button>
                <label style={{ display: 'flex', alignItems: 'center', gap: 4, fontSize: 12, color: '#aaa', marginLeft: 'auto' }}>
                  Lissage :
                  <input type="range" min={1} max={11} step={2}
                    value={smoothingWindow}
                    onChange={e => setSmoothingWindow(Number(e.target.value))}
                    disabled={computing}
                    style={{ width: 80 }} />
                  <span style={{ fontFamily: 'monospace', minWidth: 16 }}>{smoothingWindow}</span>
                </label>
                <button onClick={handleComputeAnimation} disabled={computing}>
                  Recalculer (Bary)
                </button>
                <button onClick={handleComputeARAP} disabled={computing} style={{ background: '#9333ea', color: 'white' }}>
                  Recalculer ARAP
                </button>
              </>
            )}
          </div>

          {computing && (
            <div style={{ padding: '0 16px' }}>
              <div style={{ width: '100%', height: 4, background: '#333', borderRadius: 2 }}>
                <div style={{ width: '50%', height: '100%', background: '#2563eb', borderRadius: 2 }} />
              </div>
            </div>
          )}

          {hasAnimation && (
            <>
              <div style={{ padding: '4px 16px 8px', display: 'flex', alignItems: 'center', gap: 8 }}>
                <span style={{ color: '#888', fontSize: 12 }}>Vue :</span>
                <button
                  onClick={() => setViewMode('video')}
                  style={{
                    padding: '4px 12px', fontSize: 12,
                    background: viewMode === 'video' ? '#2563eb' : '#333',
                    color: 'white', border: 'none', borderRadius: 4, cursor: 'pointer',
                  }}
                >
                  Vidéo + Mesh
                </button>
                <button
                  onClick={() => setViewMode('wireframe')}
                  style={{
                    padding: '4px 12px', fontSize: 12,
                    background: viewMode === 'wireframe' ? '#2563eb' : '#333',
                    color: 'white', border: 'none', borderRadius: 4, cursor: 'pointer',
                  }}
                >
                  Wireframe
                </button>
                <button
                  onClick={() => setViewMode('gradient')}
                  style={{
                    padding: '4px 12px', fontSize: 12,
                    background: viewMode === 'gradient' ? '#2563eb' : '#333',
                    color: 'white', border: 'none', borderRadius: 4, cursor: 'pointer',
                  }}
                >
                  Gradient
                </button>
                <span style={{ flex: 1 }} />
                <input
                  type="range"
                  min={0}
                  max={mesh.videoFramesMesh!.length - 1}
                  value={currentFrame}
                  onChange={e => { setPlaying(false); setCurrentFrame(Number(e.target.value)) }}
                  style={{ width: 200 }}
                />
                <span style={{ fontFamily: 'monospace', fontSize: 12, color: '#aaa', minWidth: 80 }}>
                  {currentFrame} / {mesh.videoFramesMesh!.length - 1}
                </span>
              </div>
              <div ref={animContainerRef} style={{ height: 400, position: 'relative' }}>
                <canvas ref={animCanvasRef} style={{ width: '100%', height: '100%' }} />
              </div>
            </>
          )}
        </div>
      )}
    </div>
  )
}
