import { useState, useEffect, useRef, useCallback } from 'react'
import Delaunator from 'delaunator'
import type { Project, Point2D, MeshData } from '../../types/project'
import type { UploadHint } from '../../db/projectsStore'
import TriangulationCanvas from '../triangulation/TriangulationCanvas'
import { useTriangulation } from '../triangulation/useTriangulation'
import { generateAutoMesh } from '../../utils/autoMeshGenerator'
import { generateTemplatePDF } from '../../utils/pdfGenerator'
import { computeAllBarycentrics } from '../../utils/barycentricUtils'
import { pointInPolygon, triangleCentroid } from '../../utils/geometry'
import type { PointType } from '../triangulation/drawingUtils'

interface Props {
  project: Project
  onSave: (project: Project, uploadOnly?: UploadHint[]) => Promise<void>
}

export default function TriangulationStep({ project, onSave }: Props) {
  const [saving, setSaving] = useState(false)
  const [imageUrl, setImageUrl] = useState<string | null>(null)
  const [density, setDensity] = useState(5)
  const [generating, setGenerating] = useState(false)
  const isAutoGenerated = useRef(false)

  const mesh = project.mesh
  const anchorPoints = mesh?.anchorPoints ?? []
  const contourIndices = mesh?.contourIndices ?? []
  const contourPolygon = contourIndices.map(i => anchorPoints[i])
  const topologyLocked = mesh?.topologyLocked ?? false

  const {
    internalPoints,
    triangles,
    addInternalPoint,
    movePoint,
    deletePoint,
    loadAutoMesh,
  } = useTriangulation(
    mesh
      ? {
          contourPoints: contourPolygon,
          internalPoints: mesh.internalPoints,
          triangles: mesh.triangles,
        }
      : undefined,
    anchorPoints.length > 0 ? anchorPoints : undefined,
    contourIndices.length > 0 ? contourIndices : undefined
  )

  useEffect(() => {
    if (!project.originalImageBlob) {
      setImageUrl(null)
      return
    }
    const url = URL.createObjectURL(project.originalImageBlob)
    setImageUrl(url)
    return () => URL.revokeObjectURL(url)
  }, [project.originalImageBlob])

  const runAutoInternalPoints = useCallback(async (d: number) => {
    if (!project.originalImageBlob) return
    setGenerating(true)
    try {
      const result = await generateAutoMesh(project.originalImageBlob, d)
      loadAutoMesh(contourPolygon, result.internalPoints)
      isAutoGenerated.current = true
    } catch (err) {
      console.error('Auto internal points failed:', err)
    } finally {
      setGenerating(false)
    }
  }, [project.originalImageBlob, loadAutoMesh, contourPolygon])

  function handleAutoInternalPoints() {
    runAutoInternalPoints(density)
  }

  function handleDensityChange(delta: number) {
    const newDensity = Math.max(1, Math.min(10, density + delta))
    setDensity(newDensity)
    if (isAutoGenerated.current) {
      runAutoInternalPoints(newDensity)
    }
  }

  function handleClearInternalPoints() {
    loadAutoMesh(contourPolygon, [])
    isAutoGenerated.current = false
  }

  const handleMovePoint = useCallback((type: PointType, index: number, p: Point2D) => {
    if (type === 'internal') {
      movePoint('internal', index, p)
    }
  }, [movePoint])

  const handleDeletePoint = useCallback((type: PointType, index: number) => {
    if (type === 'internal') {
      deletePoint('internal', index)
    }
  }, [deletePoint])

  async function handleLockTopology() {
    if (!mesh || anchorPoints.length < 3) return
    setSaving(true)
    try {
      const anchorCoords = new Float64Array(anchorPoints.length * 2)
      anchorPoints.forEach((p, i) => {
        anchorCoords[i * 2] = p.x
        anchorCoords[i * 2 + 1] = p.y
      })
      const delaunay = new Delaunator(anchorCoords)
      const anchorTriangles: [number, number, number][] = []
      for (let i = 0; i < delaunay.triangles.length; i += 3) {
        const a = delaunay.triangles[i]
        const b = delaunay.triangles[i + 1]
        const c = delaunay.triangles[i + 2]
        const centroid = triangleCentroid(anchorPoints[a], anchorPoints[b], anchorPoints[c])
        if (pointInPolygon(centroid, contourPolygon)) {
          anchorTriangles.push([a, b, c])
        }
      }

      const internalBarycentrics = computeAllBarycentrics(
        internalPoints,
        anchorPoints,
        anchorTriangles
      )

      const updatedMesh: MeshData = {
        ...mesh,
        internalPoints,
        triangles,
        topologyLocked: true,
        anchorTriangles,
        internalBarycentrics,
      }

      await onSave({ ...project, mesh: updatedMesh })
    } catch (err) {
      console.error('Failed to lock topology:', err)
      alert('Erreur : ' + (err instanceof Error ? err.message : err))
    }
    setSaving(false)
  }

  async function handleUnlockTopology() {
    if (!mesh) return
    if (!confirm('Déverrouiller la topologie supprimera les données de keyframes et d\'animation. Continuer ?')) return
    setSaving(true)
    try {
      const updatedMesh: MeshData = {
        ...mesh,
        topologyLocked: false,
        anchorTriangles: [],
        internalBarycentrics: [],
        keyframes: [],
        anchorFrames: null,
        videoFramesMesh: null,
      }
      await onSave({ ...project, mesh: updatedMesh })
    } catch (err) {
      console.error('Failed to unlock topology:', err)
    }
    setSaving(false)
  }

  async function handleSave() {
    if (!mesh) return
    setSaving(true)
    try {
      const updatedMesh: MeshData = {
        ...mesh,
        internalPoints,
        triangles,
      }
      await onSave({ ...project, mesh: updatedMesh })
    } catch (err) {
      console.error('Failed to save mesh:', err)
      alert('Erreur lors de la sauvegarde : ' + (err instanceof Error ? err.message : err))
    }
    setSaving(false)
  }

  async function handleGeneratePDF() {
    try {
      const blob = await generateTemplatePDF(project)
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${project.name}-template.pdf`
      a.click()
      URL.revokeObjectURL(url)
    } catch (err) {
      console.error('PDF generation failed:', err)
      alert('Erreur PDF : ' + (err instanceof Error ? err.message : err))
    }
  }

  if (!mesh || anchorPoints.length < 3) {
    return (
      <div className="placeholder">
        Définissez d'abord les points d'ancrage dans l'onglet précédent (minimum 3 points).
      </div>
    )
  }

  return (
    <div className="triangulation-step">
      <div className="triangulation-toolbar">
        {topologyLocked && (
          <span style={{ color: '#22c55e', fontWeight: 'bold', marginRight: 8 }}>
            🔒 Topologie verrouillée
          </span>
        )}

        {!topologyLocked && (
          <>
            <button onClick={handleAutoInternalPoints} disabled={generating}>
              {generating ? 'Génération...' : 'Auto points internes'}
            </button>

            <button
              onClick={() => handleDensityChange(-1)}
              disabled={density <= 1 || generating}
              title="Moins de points"
            >
              −
            </button>
            <span className="density-label">Densité: {density}</span>
            <button
              onClick={() => handleDensityChange(1)}
              disabled={density >= 10 || generating}
              title="Plus de points"
            >
              +
            </button>

            <span className="toolbar-separator" />

            <button onClick={handleSave} disabled={saving}>
              {saving ? 'Sauvegarde...' : 'Sauvegarder'}
            </button>
            <button
              onClick={handleLockTopology}
              disabled={saving || triangles.length === 0}
              style={{ background: '#22c55e', color: 'white' }}
            >
              Verrouiller la topologie
            </button>
            <button className="btn-danger" onClick={handleClearInternalPoints}>
              Effacer internes
            </button>
          </>
        )}

        {topologyLocked && (
          <button className="btn-danger" onClick={handleUnlockTopology} disabled={saving}>
            Déverrouiller
          </button>
        )}

        <span className="toolbar-separator" />

        <button onClick={handleGeneratePDF}>
          Télécharger PDF
        </button>

        <span className="toolbar-info">
          Anchors: {anchorPoints.length} |
          Internes: {internalPoints.length} |
          Triangles: {triangles.length}
        </span>
      </div>

      <div className="triangulation-help">
        {topologyLocked ? (
          <span>
            La topologie est verrouillée. Les points ne peuvent plus être modifiés.
            Passez à l'étape Keyframes pour animer le maillage.
          </span>
        ) : (
          <span>
            Clic gauche = ajouter un point interne | Glisser = déplacer | Clic droit = supprimer |
            Les points d'ancrage (bleus + orange) sont en lecture seule.
          </span>
        )}
      </div>

      <TriangulationCanvas
        imageUrl={imageUrl}
        contourPoints={contourPolygon}
        internalPoints={topologyLocked ? mesh.internalPoints : internalPoints}
        triangles={topologyLocked ? mesh.triangles : triangles}
        contourClosed={true}
        mode="internal"
        onAddContourPoint={() => {}}
        onInsertContourPoint={() => {}}
        onCloseContour={() => {}}
        onAddInternalPoint={topologyLocked ? () => {} : addInternalPoint}
        onMovePoint={topologyLocked ? () => {} : handleMovePoint}
        onDeletePoint={topologyLocked ? () => {} : handleDeletePoint}
        anchorPoints={anchorPoints}
        readOnlyAnchors={true}
      />
    </div>
  )
}
